# If true will allow maces to be crafted but as soon as one is crafted it will be set to false
mace: true

# If true the crafter block can craft the first mace
AllowCrafter: false

# if false you can disable it changing the mace value automatically
enabled: true